<?php declare(strict_types=1);

namespace Paneon\PhpToTypeScript\Parser;

class DeclareEnum
{
    /** @var DeclareEnumCase[] */
    protected array $cases = [];
    protected string $prefix = '';
    protected string $suffix = '';
    protected int $indent = 2;
    protected bool $asUnion = false;
    protected bool $export = false;

    public function __construct(
        protected string $name
    ) {}

    public function addCase(DeclareEnumCase $case): void
    {
        if ($this->indent) {
            $case->setIndentSize($this->indent);
        }

        $this->cases[] = $case;
    }

    public function getName(): string
    {
        return $this->prefix . $this->name . $this->suffix;
    }

    public function __toString(): string
    {
        if ($this->asUnion) {
            return $this->toUnionString();
        }

        return $this->toEnumString();
    }

    public function toEnumString(): string
    {
        $enumBody = '';
        $lastKey = count($this->cases) - 1;

        foreach ($this->cases as $key => $case) {
            $enumBody .= $case->toEnumCaseString();

            if ($key !== $lastKey) {
                $enumBody .= PHP_EOL;
            }
        }

        $exportKeyword = $this->export ? 'export ' : '';
        $name = $this->getName();

        return <<< HEREDOC
/* This file was automatically generated by the typescript:generate command. */
{$exportKeyword}enum {$name} {
{$enumBody}
}
HEREDOC;
    }

    public function toUnionString(): string
    {
        $unionParts = [];

        foreach ($this->cases as $case) {
            $unionParts[] = $case->toUnionPart();
        }

        $unionType = implode(' | ', $unionParts);
        $exportKeyword = $this->export ? 'export ' : '';
        $name = $this->getName();

        return <<< HEREDOC
/* This file was automatically generated by the typescript:generate command. */
{$exportKeyword}type {$name} = {$unionType};
HEREDOC;
    }

    public function setIndent(int $indent): DeclareEnum
    {
        $this->indent = $indent;
        return $this;
    }

    public function setPrefix(string $prefix): DeclareEnum
    {
        $this->prefix = $prefix;
        return $this;
    }

    public function setSuffix(string $suffix): DeclareEnum
    {
        $this->suffix = $suffix;
        return $this;
    }

    public function setAsUnion(bool $asUnion): DeclareEnum
    {
        $this->asUnion = $asUnion;
        return $this;
    }

    public function setExport(bool $export): DeclareEnum
    {
        $this->export = $export;
        return $this;
    }
}
